package View;

import Control.AlunosControl;
import Model.Aluno;
import Model.DadosException;
import Model.Pagamento;
import javax.swing.JOptionPane;
import Model.Data;

public class frmPagamento extends javax.swing.JFrame {

    /**
     * Creates new form FormasPag
     */
    Aluno a;
    public frmPagamento(Aluno a) {
        initComponents();
        this.a = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbModoPag = new javax.swing.JComboBox<>();
        txtCart1 = new javax.swing.JTextField();
        txtCart2 = new javax.swing.JTextField();
        txtCart3 = new javax.swing.JTextField();
        txtCart4 = new javax.swing.JTextField();
        txtNomeCartao = new javax.swing.JTextField();
        txtCodSeg = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Pagamento");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Formas de Pagamento");

        jLabel3.setText("N° do cartão :");

        jLabel4.setText("Nome no cartão :");

        jLabel6.setText("Código de segurança:");

        jLabel7.setText("Escolha o modo de pagamento :");

        cbModoPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensal", "Bimestral", "Semestral", "Anual" }));

        txtCart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCart1ActionPerformed(evt);
            }
        });

        txtNomeCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCartaoActionPerformed(evt);
            }
        });

        txtCodSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodSegActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalvarMousePressed(evt);
            }
        });

        jLabel5.setText("Vencimento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(5, 5, 5)
                                    .addComponent(txtCart1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCart2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCart3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCart4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNomeCartao))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbModoPag, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbModoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNomeCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(397, 352));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCart1ActionPerformed

    private void txtNomeCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCartaoActionPerformed

    private void txtCodSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodSegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodSegActionPerformed

    private void btnSalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMousePressed
        // TODO add your handling code here:
        if((!txtCart1.getText().isEmpty() || !txtCart2.getText().isEmpty() || !txtCart3.getText().isEmpty()
            ||!txtCart4.getText().isEmpty()) && !txtNomeCartao.getText().isEmpty() && !txtMes.getText().isEmpty()
            && !txtAno.getText().isEmpty() && !txtCodSeg.getText().isEmpty()) {
            
            Pagamento p = new Pagamento();
                
            int mes, ano, codSeg, cartao;
            String numCartao  = txtCart1.getText() + txtCart2.getText() +
                    txtCart3.getText() + txtCart4.getText();;
            
            try{
                mes = Integer.parseInt(txtMes.getText());
                ano = Integer.parseInt(txtAno.getText());
                codSeg = Integer.parseInt(txtCodSeg.getText());            
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Número do Cartão, Vencimento e Código de Segurança precisam ser números!");
                limpar();
                return;
            }
            
            String nomeCartao = txtNomeCartao.getText();
            String modoPag = cbModoPag.getSelectedItem().toString();

            Data data = new Data();
            data.setAno(ano);
            data.setMes(mes);

            if(!numCartao.isEmpty()){                
                if (numCartao.length() != 16 || mes < 1 || mes > 12 || ano < 2021 
                   || ano > 2050 || codSeg < 100 || codSeg > 999){
                    JOptionPane.showMessageDialog(null, "Cartão Inválido!"); 
                    limpar();
                    txtCart1.requestFocus();

                } else {
                    try{
                        p.setNumCartao(numCartao);
                    } catch (DadosException e){
                        limpar();
                        return;
                    }
                    p.setNomeCartao(nomeCartao);                

                    p.setVencimento(data);
                    p.setCodSeg(codSeg);
                    p.setModoPag(modoPag);

                    this.a.setPagamento(p);
                    
                    AlunosControl ac = new AlunosControl();
                    ac.cadastrarAluno(a);
                    
                    JOptionPane.showMessageDialog(null, "Forma de pagamento salvo!");   
                    this.dispose();
                    frmCadAluno al = new frmCadAluno();
                    al.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Digite um número de cartão");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Dados obrigatórios faltando!");
        }
    }//GEN-LAST:event_btnSalvarMousePressed

    public void limpar(){
        txtCart1.setText("");
        txtCart2.setText("");
        txtCart3.setText("");
        txtCart4.setText("");
        txtNomeCartao.setText("");
        txtCodSeg.setText("");
        txtMes.setText("");
        txtAno.setText("");
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbModoPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCart1;
    private javax.swing.JTextField txtCart2;
    private javax.swing.JTextField txtCart3;
    private javax.swing.JTextField txtCart4;
    private javax.swing.JTextField txtCodSeg;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNomeCartao;
    // End of variables declaration//GEN-END:variables
}
