package View;

import Control.ImagemControl;

public class frmPrincipal extends javax.swing.JFrame {

    
    ImagemControl im;
    /**
     * Creates new form Principal
     */
    
    public frmPrincipal() {
        initComponents();
        
        
        im = new ImagemControl();
        carregarImagem();
    }

    private void carregarImagem(){
        String path = im.obterImagem();
        
        lbImagem.setIcon(new javax.swing.ImageIcon(path));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadAlunos = new javax.swing.JButton();
        btnCadCursos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbEscolaDanca = new javax.swing.JLabel();
        lbImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        setPreferredSize(new java.awt.Dimension(1280, 853));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 853));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnCadAlunos.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        btnCadAlunos.setText("Cadastrar Alunos");
        btnCadAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadAlunosMousePressed(evt);
            }
        });

        btnCadCursos.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        btnCadCursos.setText("Cadastrar Cursos");
        btnCadCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadCursosMousePressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jButton1.setText("Buscar Aluno");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnCadCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(300, 500, 690, 250);

        lbEscolaDanca.setFont(new java.awt.Font("Ubuntu", 0, 80)); // NOI18N
        lbEscolaDanca.setForeground(new java.awt.Color(255, 255, 255));
        lbEscolaDanca.setText("ESCOLA DE DANÇA");
        getContentPane().add(lbEscolaDanca);
        lbEscolaDanca.setBounds(290, 30, 990, 93);

        lbImagem.setText("jLabel1");
        getContentPane().add(lbImagem);
        lbImagem.setBounds(0, 0, 1280, 850);

        setSize(new java.awt.Dimension(1273, 878));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadCursosMousePressed
        // TODO add your handling code here:
        frmCadCurso curso = new frmCadCurso();
        curso.setVisible(true);
    }//GEN-LAST:event_btnCadCursosMousePressed

    private void btnCadAlunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadAlunosMousePressed
        // TODO add your handling code here:
        frmCadAluno aluno = new frmCadAluno();
        aluno.setVisible(true);
    }//GEN-LAST:event_btnCadAlunosMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        
        frmBuscaAluno busca = new frmBuscaAluno();
        busca.setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAlunos;
    private javax.swing.JButton btnCadCursos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbEscolaDanca;
    private javax.swing.JLabel lbImagem;
    // End of variables declaration//GEN-END:variables
}
